variables:
  BINTRAY_STAGING: "https://staging-packages.unity.com"
  GIT_SSL_NO_VERIFY: "true"
  XRSDK_BUILD: "release"

stages:
  - build
  - package

OSX_Build:
  stage: build
  tags:
    - buildfarm
    - darwin
  script:
    - cd Source~
    - mono bee.exe
  artifacts:
    paths:
      - Runtime/Android/UnityARCore.aar
      - Runtime/Android/UnityARCore.aar.meta
# Important! Do not remove this after_script as the VM will live for 12 hours before being destroyed!
  after_script:
    - /opt/post_build_script.sh

Package:
  stage: package
  image: node:6.10.0
  dependencies:
    - OSX_Build
  script:
    - npm pack .
  except:
    - tags
  artifacts:
    paths:
      - com.unity.xr.arcore*.tgz

Publish:
  stage: package
  image: node:6.10.0
  dependencies:
    - OSX_Build
  script:
    # Update the package version to the tag, if it's set.
    - curl -u $USER_NAME:$API_KEY https://staging-packages.unity.com/auth > .npmrc
    - npm publish
  only:
    - tags
